# config/packages/vich_uploader.yaml or app/config/config.yml
vich_uploader:
  db_driver: orm

  mappings:
    document_image:
      uri_prefix: /images/documents
      upload_destination: '%kernel.project_dir%/public/images/documents'
      namer: Vich\UploaderBundle\Naming\UniqidNamer