<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTsaDx3X\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTsaDx3X/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTsaDx3X.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTsaDx3X\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerTsaDx3X\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'TsaDx3X',
    'container.build_id' => 'b1691c1c',
    'container.build_time' => 1580742336,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTsaDx3X');
