<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRy4nBTQ\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRy4nBTQ/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRy4nBTQ.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRy4nBTQ\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerRy4nBTQ\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'Ry4nBTQ',
    'container.build_id' => 'bc7189b7',
    'container.build_time' => 1582057648,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRy4nBTQ');
