<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format'], ['variable', '/', '\\d+', 'code'], ['text', '/_error']], [], []],
    'modify' => [[], ['_controller' => 'App\\Controller\\ModifyController::index'], [], [['text', '/modify']], [], []],
    'ajouter' => [[], ['_controller' => 'App\\Controller\\ModifyController::ajouter'], [], [['text', '/modify/add']], [], []],
    'editer' => [[], ['_controller' => 'App\\Controller\\ModifyController::edit'], [], [['text', '/modify/editer']], [], []],
    'home' => [[], ['_controller' => 'App\\Controller\\SiteHacceScolController::home'], [], [['text', '/']], [], []],
    'site_index' => [[], ['_controller' => 'App\\Controller\\SiteHacceScolController::index'], [], [['text', '/site_hacce_scol/parcourir']], [], []],
    'site_show' => [['id'], ['_controller' => 'App\\Controller\\SiteHacceScolController::show'], [], [['variable', '/', '[^/]++', 'id'], ['text', '/site_hacce_scol']], [], []],
];
